In [11]:
import numpy as np
import pandas as pd

In [12]:
df=pd.read_csv('covid_toy.csv')
df.head(5)

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [13]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [14]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [16]:
X_train

age  gender  fever   cough       city
49   44    Male  104.0    Mild     Mumbai
97   20  Female  101.0    Mild  Bangalore
90   59  Female   99.0  Strong      Delhi
68   54  Female  104.0  Strong    Kolkata
71   75  Female  104.0  Strong      Delhi
..  ...     ...    ...     ...        ...
19   42  Female    NaN  Strong  Bangalore
82   24    Male   98.0    Mild    Kolkata
15   70    Male  103.0  Strong    Kolkata
35   82  Female  102.0  Strong  Bangalore
83   17  Female  104.0    Mild    Kolkata

[80 rows x 5 columns]

#### AAM ZINDAGI KI SARE COLUMNS KO ALAG ALAG CHEEJ KRO OR LAST M CONACTENATE KRO

In [19]:
si=SimpleImputer()
X_train_fever=si.fit_transform(X_train[['fever']])
X_test_fever=si.fit_transform(X_test[['fever']])


In [25]:
# ORDINAL ENCODING FOR COUGH
oe=OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']])
X_test_cough=oe.transform(X_test[['cough']])

In [21]:
# ONE HOT ENCODING FOR GENDER AND CITY
ohe=OneHotEncoder()
X_train_gender_city=ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city=ohe.fit_transform(X_test[['gender','city']])

In [22]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [26]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city.toarray(),X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city.toarray(),X_test_cough),axis=1)

X_train_transformed

array([[ 44.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ,   1.        ,
          0.        ],
       [ 20.        , 101.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ,   0.        ,
          0.        ],
       [ 59.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
          1.        ],
       [ 54.        , 104.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ,   0.        ,
          1.        ],
       [ 75.        , 104.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
          1.        ],
       [ 19.        , 101.        ,   0.        ,   1.        ,
          0.        ,   1.        ,   0.        ,   0.        ,
          0.        ],
       [  5.        ,  98.        ,   1.        ,   0.        ,
          0.        ,   0.    

#### MENTOS ZINDAGI

In [27]:
from sklearn.compose import ColumnTransformer

In [29]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [31]:

transformer.fit_transform(X_train)

array([[104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  44.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  20.        ],
       [ 99.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  59.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  54.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  75.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  19.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   5.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  12.        ],
       [101.        ,   0.        ,   0.        ,   1.        ,
          0.    

In [32]:
transformer.transform(X_test)

array([[ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  64.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  65.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  50.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  48.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  60.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  69.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  16.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.    